version: '3.7'

services:
  app:
    build:
      context: ./app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=0
      - SECRET_KEY=sampleS3cR3t!
      - ALLOWED_HOSTS=127.0.0.1,localhost,[::1]
    volumes:
    - static_volume:/app/static
    - media_volume:/app/media

  proxy:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
    - static_volume:/app/static
    - media_volume:/app/media
    depends_on:
      - app


volumes:
  static_volume:
  media_volume: