# Generated by Django 3.1.5 on 2021-02-12 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssistiveDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Assistive Devices',
                'verbose_name_plural': 'Assistive Device',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Disability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Disability',
                'verbose_name_plural': 'Disabilities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DisabiltiyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('assistive_devices', models.ManyToManyField(blank=True, to='disability.AssistiveDevice')),
                ('disability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disability.disability')),
            ],
            options={
                'verbose_name': 'Disability Detail',
                'verbose_name_plural': 'Disability Detail',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DisabilityQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('question_type', models.IntegerField(choices=[(1, 'Yes No'), (2, 'Essay')])),
                ('mandatory', models.BooleanField(default=False)),
                ('disability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disability.disability')),
            ],
            options={
                'verbose_name': 'Disability Question',
                'verbose_name_plural': 'Disability Questions',
                'managed': True,
            },
        ),
    ]
