# Generated by Django 3.1.5 on 2021-02-08 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pwd_id', models.CharField(help_text='Persons with Disability Number (RR-PPMM-BBB-NNNNNNN)', max_length=35, verbose_name='PWD No.')),
                ('last_name', models.CharField(max_length=35)),
                ('first_name', models.CharField(max_length=35)),
                ('middle_name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_one', models.CharField(max_length=25)),
                ('address_line_two', models.CharField(max_length=25)),
                ('purok', models.CharField(max_length=25, verbose_name='Purok')),
                ('default', models.BooleanField(default=False)),
                ('barangy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.barangy')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person')),
            ],
        ),
    ]
