# Generated by Django 3.1.5 on 2021-02-12 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pwd_id', models.CharField(help_text='Persons with Disability Number (RR-PPMM-BBB-NNNNNNN)', max_length=35, verbose_name='PWD No.')),
                ('last_name', models.CharField(max_length=35)),
                ('first_name', models.CharField(max_length=35)),
                ('middle_name', models.CharField(max_length=35)),
                ('suffix', models.IntegerField(choices=[(0, 'Jr'), (1, 'Sr'), (2, 'Ii'), (3, 'Iii'), (4, 'Iv'), (5, 'V')], null=True)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], null=True)),
                ('birthday', models.DateField()),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('religion', models.IntegerField(choices=[(0, 'Christian'), (1, 'Muslim'), (2, 'Buddist')], null=True)),
                ('ethnic_group', models.IntegerField(choices=[(0, 'Igorot'), (1, 'Bicolano')], null=True)),
                ('civil_status', models.IntegerField(choices=[(0, 'Single'), (1, 'Married'), (2, 'Separated'), (3, 'Live In'), (4, 'Widow')], null=True)),
                ('blood_type', models.IntegerField(choices=[(0, 'A Plus'), (1, 'A Minus'), (2, 'Ab Plus'), (3, 'Ab Minus'), (4, 'B Plus'), (5, 'B Minus'), (6, 'O Plus'), (7, 'O Minus')], null=True)),
                ('sss_no', models.CharField(help_text='Social Security Number', max_length=25, verbose_name='SSS No.')),
                ('gsis_no', models.CharField(help_text='Please provide if any', max_length=25, verbose_name='GSIS No.')),
                ('pagibig_no', models.CharField(max_length=25)),
                ('philhealth_no', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=25)),
                ('mobile_number', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('status', models.IntegerField(choices=[(0, 'Employed'), (1, 'Unemployed'), (2, 'Self Employed')])),
                ('category', models.IntegerField(choices=[(0, 'Government'), (1, 'Private')], null=True)),
                ('type_of_emp', models.IntegerField(choices=[(0, 'Permanent Or Regular'), (1, 'Seasonal'), (2, 'Casual'), (3, 'Emergency')], null=True)),
                ('occupation', models.IntegerField(choices=[(0, 'Manager'), (1, 'Professional'), (2, 'Technical And Associate Professional'), (3, 'Clerical Support Workers'), (4, 'Service And Sales Workers'), (5, 'Skilled Agricultural Forestry And Fishery Workers'), (6, 'Craft And Related Trade Workers'), (7, 'Plant And Machine Operators And Assemblers'), (8, 'Elementary Occupations'), (9, 'Armed Forces Occupations'), (10, 'Others')], null=True)),
                ('others', models.CharField(max_length=25)),
                ('org_aff', models.CharField(max_length=25, verbose_name='Organization Affiliated')),
                ('org_contact_person', models.CharField(max_length=25, verbose_name='Contact Person')),
                ('org_address', models.CharField(max_length=25, verbose_name='Office Address')),
                ('org_tel', models.CharField(max_length=25, verbose_name='Tel. Nos.')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_one', models.CharField(max_length=25)),
                ('address_line_two', models.CharField(max_length=25)),
                ('purok', models.CharField(max_length=25, verbose_name='Purok')),
                ('default', models.BooleanField(default=False)),
                ('barangy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.barangy')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person')),
            ],
        ),
    ]
