# Generated by Django 3.1.5 on 2021-02-12 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_line_one',
            new_name='house_no_and_street',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_line_two',
        ),
    ]
